// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package synthetics

import (
	"context"
	"reflect"

	"errors"
	"github.com/displayr/pulumi-signalfx-synthetics/sdk/go/synthetics/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the synthetics package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// Splunk Observability API Key. Will pull from `OBSERVABILITY_API_TOKEN` environment variable if available.
	Apikey pulumi.StringPtrOutput `pulumi:"apikey"`
	// One of: `observability` or `rigor`
	Product pulumi.StringOutput `pulumi:"product"`
	// Splunk Observability Realm (E.G. `us1`). Will pull from `REALM` environment variable if available. For Rigor use realm
	// rigor
	Realm pulumi.StringOutput `pulumi:"realm"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Product == nil {
		return nil, errors.New("invalid value for required argument 'Product'")
	}
	if args.Realm == nil {
		return nil, errors.New("invalid value for required argument 'Realm'")
	}
	if args.Apikey == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "OBSERVABILITY_API_TOKEN"); d != nil {
			args.Apikey = pulumi.StringPtr(d.(string))
		}
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:synthetics", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Splunk Observability API Key. Will pull from `OBSERVABILITY_API_TOKEN` environment variable if available.
	Apikey *string `pulumi:"apikey"`
	// One of: `observability` or `rigor`
	Product string `pulumi:"product"`
	// Splunk Observability Realm (E.G. `us1`). Will pull from `REALM` environment variable if available. For Rigor use realm
	// rigor
	Realm string `pulumi:"realm"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Splunk Observability API Key. Will pull from `OBSERVABILITY_API_TOKEN` environment variable if available.
	Apikey pulumi.StringPtrInput
	// One of: `observability` or `rigor`
	Product pulumi.StringInput
	// Splunk Observability Realm (E.G. `us1`). Will pull from `REALM` environment variable if available. For Rigor use realm
	// rigor
	Realm pulumi.StringInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Splunk Observability API Key. Will pull from `OBSERVABILITY_API_TOKEN` environment variable if available.
func (o ProviderOutput) Apikey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Apikey }).(pulumi.StringPtrOutput)
}

// One of: `observability` or `rigor`
func (o ProviderOutput) Product() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Product }).(pulumi.StringOutput)
}

// Splunk Observability Realm (E.G. `us1`). Will pull from `REALM` environment variable if available. For Rigor use realm
// rigor
func (o ProviderOutput) Realm() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Realm }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
