// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package synthetics

import (
	"context"
	"reflect"

	"errors"
	"github.com/displayr/pulumi-signalfx-synthetics/sdk/go/synthetics/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// **Note**: This is a Rigor (Legacy) resource
type SyntheticsCreateBrowserCheck struct {
	pulumi.CustomResourceState

	AutoRetry            pulumi.BoolPtrOutput                                     `pulumi:"autoRetry"`
	AutoUpdateUserAgent  pulumi.BoolPtrOutput                                     `pulumi:"autoUpdateUserAgent"`
	BlackoutPeriods      SyntheticsCreateBrowserCheckBlackoutPeriodArrayOutput    `pulumi:"blackoutPeriods"`
	Browsers             SyntheticsCreateBrowserCheckBrowserArrayOutput           `pulumi:"browsers"`
	CheckConnections     SyntheticsCreateBrowserCheckCheckConnectionArrayOutput   `pulumi:"checkConnections"`
	Cookies              SyntheticsCreateBrowserCheckCookieArrayOutput            `pulumi:"cookies"`
	DnsOverrides         SyntheticsCreateBrowserCheckDnsOverrideArrayOutput       `pulumi:"dnsOverrides"`
	Enabled              pulumi.BoolPtrOutput                                     `pulumi:"enabled"`
	EnforceSslValidation pulumi.BoolPtrOutput                                     `pulumi:"enforceSslValidation"`
	ExcludedFiles        SyntheticsCreateBrowserCheckExcludedFileArrayOutput      `pulumi:"excludedFiles"`
	Frequency            pulumi.IntOutput                                         `pulumi:"frequency"`
	HttpMethod           pulumi.StringPtrOutput                                   `pulumi:"httpMethod"`
	HttpRequestBody      pulumi.StringPtrOutput                                   `pulumi:"httpRequestBody"`
	HttpRequestHeaders   SyntheticsCreateBrowserCheckHttpRequestHeaderArrayOutput `pulumi:"httpRequestHeaders"`
	Integrations         pulumi.IntArrayOutput                                    `pulumi:"integrations"`
	JavascriptFiles      SyntheticsCreateBrowserCheckJavascriptFileArrayOutput    `pulumi:"javascriptFiles"`
	LastUpdated          pulumi.StringOutput                                      `pulumi:"lastUpdated"`
	Locations            pulumi.IntArrayOutput                                    `pulumi:"locations"`
	Name                 pulumi.StringOutput                                      `pulumi:"name"`
	Notifications        SyntheticsCreateBrowserCheckNotificationArrayOutput      `pulumi:"notifications"`
	RoundRobin           pulumi.BoolPtrOutput                                     `pulumi:"roundRobin"`
	Steps                SyntheticsCreateBrowserCheckStepArrayOutput              `pulumi:"steps"`
	SuccessCriterias     SyntheticsCreateBrowserCheckSuccessCriteriaArrayOutput   `pulumi:"successCriterias"`
	Tags                 pulumi.StringArrayOutput                                 `pulumi:"tags"`
	ThresholdMonitors    SyntheticsCreateBrowserCheckThresholdMonitorArrayOutput  `pulumi:"thresholdMonitors"`
	Type                 pulumi.StringPtrOutput                                   `pulumi:"type"`
	Url                  pulumi.StringOutput                                      `pulumi:"url"`
	UserAgent            pulumi.StringPtrOutput                                   `pulumi:"userAgent"`
	Viewports            SyntheticsCreateBrowserCheckViewportArrayOutput          `pulumi:"viewports"`
	WaitForFullMetrics   pulumi.BoolPtrOutput                                     `pulumi:"waitForFullMetrics"`
}

// NewSyntheticsCreateBrowserCheck registers a new resource with the given unique name, arguments, and options.
func NewSyntheticsCreateBrowserCheck(ctx *pulumi.Context,
	name string, args *SyntheticsCreateBrowserCheckArgs, opts ...pulumi.ResourceOption) (*SyntheticsCreateBrowserCheck, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Frequency == nil {
		return nil, errors.New("invalid value for required argument 'Frequency'")
	}
	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SyntheticsCreateBrowserCheck
	err := ctx.RegisterResource("synthetics:index/syntheticsCreateBrowserCheck:SyntheticsCreateBrowserCheck", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSyntheticsCreateBrowserCheck gets an existing SyntheticsCreateBrowserCheck resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSyntheticsCreateBrowserCheck(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SyntheticsCreateBrowserCheckState, opts ...pulumi.ResourceOption) (*SyntheticsCreateBrowserCheck, error) {
	var resource SyntheticsCreateBrowserCheck
	err := ctx.ReadResource("synthetics:index/syntheticsCreateBrowserCheck:SyntheticsCreateBrowserCheck", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SyntheticsCreateBrowserCheck resources.
type syntheticsCreateBrowserCheckState struct {
	AutoRetry            *bool                                           `pulumi:"autoRetry"`
	AutoUpdateUserAgent  *bool                                           `pulumi:"autoUpdateUserAgent"`
	BlackoutPeriods      []SyntheticsCreateBrowserCheckBlackoutPeriod    `pulumi:"blackoutPeriods"`
	Browsers             []SyntheticsCreateBrowserCheckBrowser           `pulumi:"browsers"`
	CheckConnections     []SyntheticsCreateBrowserCheckCheckConnection   `pulumi:"checkConnections"`
	Cookies              []SyntheticsCreateBrowserCheckCookie            `pulumi:"cookies"`
	DnsOverrides         []SyntheticsCreateBrowserCheckDnsOverride       `pulumi:"dnsOverrides"`
	Enabled              *bool                                           `pulumi:"enabled"`
	EnforceSslValidation *bool                                           `pulumi:"enforceSslValidation"`
	ExcludedFiles        []SyntheticsCreateBrowserCheckExcludedFile      `pulumi:"excludedFiles"`
	Frequency            *int                                            `pulumi:"frequency"`
	HttpMethod           *string                                         `pulumi:"httpMethod"`
	HttpRequestBody      *string                                         `pulumi:"httpRequestBody"`
	HttpRequestHeaders   []SyntheticsCreateBrowserCheckHttpRequestHeader `pulumi:"httpRequestHeaders"`
	Integrations         []int                                           `pulumi:"integrations"`
	JavascriptFiles      []SyntheticsCreateBrowserCheckJavascriptFile    `pulumi:"javascriptFiles"`
	LastUpdated          *string                                         `pulumi:"lastUpdated"`
	Locations            []int                                           `pulumi:"locations"`
	Name                 *string                                         `pulumi:"name"`
	Notifications        []SyntheticsCreateBrowserCheckNotification      `pulumi:"notifications"`
	RoundRobin           *bool                                           `pulumi:"roundRobin"`
	Steps                []SyntheticsCreateBrowserCheckStep              `pulumi:"steps"`
	SuccessCriterias     []SyntheticsCreateBrowserCheckSuccessCriteria   `pulumi:"successCriterias"`
	Tags                 []string                                        `pulumi:"tags"`
	ThresholdMonitors    []SyntheticsCreateBrowserCheckThresholdMonitor  `pulumi:"thresholdMonitors"`
	Type                 *string                                         `pulumi:"type"`
	Url                  *string                                         `pulumi:"url"`
	UserAgent            *string                                         `pulumi:"userAgent"`
	Viewports            []SyntheticsCreateBrowserCheckViewport          `pulumi:"viewports"`
	WaitForFullMetrics   *bool                                           `pulumi:"waitForFullMetrics"`
}

type SyntheticsCreateBrowserCheckState struct {
	AutoRetry            pulumi.BoolPtrInput
	AutoUpdateUserAgent  pulumi.BoolPtrInput
	BlackoutPeriods      SyntheticsCreateBrowserCheckBlackoutPeriodArrayInput
	Browsers             SyntheticsCreateBrowserCheckBrowserArrayInput
	CheckConnections     SyntheticsCreateBrowserCheckCheckConnectionArrayInput
	Cookies              SyntheticsCreateBrowserCheckCookieArrayInput
	DnsOverrides         SyntheticsCreateBrowserCheckDnsOverrideArrayInput
	Enabled              pulumi.BoolPtrInput
	EnforceSslValidation pulumi.BoolPtrInput
	ExcludedFiles        SyntheticsCreateBrowserCheckExcludedFileArrayInput
	Frequency            pulumi.IntPtrInput
	HttpMethod           pulumi.StringPtrInput
	HttpRequestBody      pulumi.StringPtrInput
	HttpRequestHeaders   SyntheticsCreateBrowserCheckHttpRequestHeaderArrayInput
	Integrations         pulumi.IntArrayInput
	JavascriptFiles      SyntheticsCreateBrowserCheckJavascriptFileArrayInput
	LastUpdated          pulumi.StringPtrInput
	Locations            pulumi.IntArrayInput
	Name                 pulumi.StringPtrInput
	Notifications        SyntheticsCreateBrowserCheckNotificationArrayInput
	RoundRobin           pulumi.BoolPtrInput
	Steps                SyntheticsCreateBrowserCheckStepArrayInput
	SuccessCriterias     SyntheticsCreateBrowserCheckSuccessCriteriaArrayInput
	Tags                 pulumi.StringArrayInput
	ThresholdMonitors    SyntheticsCreateBrowserCheckThresholdMonitorArrayInput
	Type                 pulumi.StringPtrInput
	Url                  pulumi.StringPtrInput
	UserAgent            pulumi.StringPtrInput
	Viewports            SyntheticsCreateBrowserCheckViewportArrayInput
	WaitForFullMetrics   pulumi.BoolPtrInput
}

func (SyntheticsCreateBrowserCheckState) ElementType() reflect.Type {
	return reflect.TypeOf((*syntheticsCreateBrowserCheckState)(nil)).Elem()
}

type syntheticsCreateBrowserCheckArgs struct {
	AutoRetry            *bool                                           `pulumi:"autoRetry"`
	AutoUpdateUserAgent  *bool                                           `pulumi:"autoUpdateUserAgent"`
	BlackoutPeriods      []SyntheticsCreateBrowserCheckBlackoutPeriod    `pulumi:"blackoutPeriods"`
	Browsers             []SyntheticsCreateBrowserCheckBrowser           `pulumi:"browsers"`
	CheckConnections     []SyntheticsCreateBrowserCheckCheckConnection   `pulumi:"checkConnections"`
	Cookies              []SyntheticsCreateBrowserCheckCookie            `pulumi:"cookies"`
	DnsOverrides         []SyntheticsCreateBrowserCheckDnsOverride       `pulumi:"dnsOverrides"`
	Enabled              *bool                                           `pulumi:"enabled"`
	EnforceSslValidation *bool                                           `pulumi:"enforceSslValidation"`
	ExcludedFiles        []SyntheticsCreateBrowserCheckExcludedFile      `pulumi:"excludedFiles"`
	Frequency            int                                             `pulumi:"frequency"`
	HttpMethod           *string                                         `pulumi:"httpMethod"`
	HttpRequestBody      *string                                         `pulumi:"httpRequestBody"`
	HttpRequestHeaders   []SyntheticsCreateBrowserCheckHttpRequestHeader `pulumi:"httpRequestHeaders"`
	Integrations         []int                                           `pulumi:"integrations"`
	JavascriptFiles      []SyntheticsCreateBrowserCheckJavascriptFile    `pulumi:"javascriptFiles"`
	LastUpdated          *string                                         `pulumi:"lastUpdated"`
	Locations            []int                                           `pulumi:"locations"`
	Name                 *string                                         `pulumi:"name"`
	Notifications        []SyntheticsCreateBrowserCheckNotification      `pulumi:"notifications"`
	RoundRobin           *bool                                           `pulumi:"roundRobin"`
	Steps                []SyntheticsCreateBrowserCheckStep              `pulumi:"steps"`
	SuccessCriterias     []SyntheticsCreateBrowserCheckSuccessCriteria   `pulumi:"successCriterias"`
	Tags                 []string                                        `pulumi:"tags"`
	ThresholdMonitors    []SyntheticsCreateBrowserCheckThresholdMonitor  `pulumi:"thresholdMonitors"`
	Type                 *string                                         `pulumi:"type"`
	Url                  string                                          `pulumi:"url"`
	UserAgent            *string                                         `pulumi:"userAgent"`
	Viewports            []SyntheticsCreateBrowserCheckViewport          `pulumi:"viewports"`
	WaitForFullMetrics   *bool                                           `pulumi:"waitForFullMetrics"`
}

// The set of arguments for constructing a SyntheticsCreateBrowserCheck resource.
type SyntheticsCreateBrowserCheckArgs struct {
	AutoRetry            pulumi.BoolPtrInput
	AutoUpdateUserAgent  pulumi.BoolPtrInput
	BlackoutPeriods      SyntheticsCreateBrowserCheckBlackoutPeriodArrayInput
	Browsers             SyntheticsCreateBrowserCheckBrowserArrayInput
	CheckConnections     SyntheticsCreateBrowserCheckCheckConnectionArrayInput
	Cookies              SyntheticsCreateBrowserCheckCookieArrayInput
	DnsOverrides         SyntheticsCreateBrowserCheckDnsOverrideArrayInput
	Enabled              pulumi.BoolPtrInput
	EnforceSslValidation pulumi.BoolPtrInput
	ExcludedFiles        SyntheticsCreateBrowserCheckExcludedFileArrayInput
	Frequency            pulumi.IntInput
	HttpMethod           pulumi.StringPtrInput
	HttpRequestBody      pulumi.StringPtrInput
	HttpRequestHeaders   SyntheticsCreateBrowserCheckHttpRequestHeaderArrayInput
	Integrations         pulumi.IntArrayInput
	JavascriptFiles      SyntheticsCreateBrowserCheckJavascriptFileArrayInput
	LastUpdated          pulumi.StringPtrInput
	Locations            pulumi.IntArrayInput
	Name                 pulumi.StringPtrInput
	Notifications        SyntheticsCreateBrowserCheckNotificationArrayInput
	RoundRobin           pulumi.BoolPtrInput
	Steps                SyntheticsCreateBrowserCheckStepArrayInput
	SuccessCriterias     SyntheticsCreateBrowserCheckSuccessCriteriaArrayInput
	Tags                 pulumi.StringArrayInput
	ThresholdMonitors    SyntheticsCreateBrowserCheckThresholdMonitorArrayInput
	Type                 pulumi.StringPtrInput
	Url                  pulumi.StringInput
	UserAgent            pulumi.StringPtrInput
	Viewports            SyntheticsCreateBrowserCheckViewportArrayInput
	WaitForFullMetrics   pulumi.BoolPtrInput
}

func (SyntheticsCreateBrowserCheckArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*syntheticsCreateBrowserCheckArgs)(nil)).Elem()
}

type SyntheticsCreateBrowserCheckInput interface {
	pulumi.Input

	ToSyntheticsCreateBrowserCheckOutput() SyntheticsCreateBrowserCheckOutput
	ToSyntheticsCreateBrowserCheckOutputWithContext(ctx context.Context) SyntheticsCreateBrowserCheckOutput
}

func (*SyntheticsCreateBrowserCheck) ElementType() reflect.Type {
	return reflect.TypeOf((**SyntheticsCreateBrowserCheck)(nil)).Elem()
}

func (i *SyntheticsCreateBrowserCheck) ToSyntheticsCreateBrowserCheckOutput() SyntheticsCreateBrowserCheckOutput {
	return i.ToSyntheticsCreateBrowserCheckOutputWithContext(context.Background())
}

func (i *SyntheticsCreateBrowserCheck) ToSyntheticsCreateBrowserCheckOutputWithContext(ctx context.Context) SyntheticsCreateBrowserCheckOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SyntheticsCreateBrowserCheckOutput)
}

// SyntheticsCreateBrowserCheckArrayInput is an input type that accepts SyntheticsCreateBrowserCheckArray and SyntheticsCreateBrowserCheckArrayOutput values.
// You can construct a concrete instance of `SyntheticsCreateBrowserCheckArrayInput` via:
//
//	SyntheticsCreateBrowserCheckArray{ SyntheticsCreateBrowserCheckArgs{...} }
type SyntheticsCreateBrowserCheckArrayInput interface {
	pulumi.Input

	ToSyntheticsCreateBrowserCheckArrayOutput() SyntheticsCreateBrowserCheckArrayOutput
	ToSyntheticsCreateBrowserCheckArrayOutputWithContext(context.Context) SyntheticsCreateBrowserCheckArrayOutput
}

type SyntheticsCreateBrowserCheckArray []SyntheticsCreateBrowserCheckInput

func (SyntheticsCreateBrowserCheckArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SyntheticsCreateBrowserCheck)(nil)).Elem()
}

func (i SyntheticsCreateBrowserCheckArray) ToSyntheticsCreateBrowserCheckArrayOutput() SyntheticsCreateBrowserCheckArrayOutput {
	return i.ToSyntheticsCreateBrowserCheckArrayOutputWithContext(context.Background())
}

func (i SyntheticsCreateBrowserCheckArray) ToSyntheticsCreateBrowserCheckArrayOutputWithContext(ctx context.Context) SyntheticsCreateBrowserCheckArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SyntheticsCreateBrowserCheckArrayOutput)
}

// SyntheticsCreateBrowserCheckMapInput is an input type that accepts SyntheticsCreateBrowserCheckMap and SyntheticsCreateBrowserCheckMapOutput values.
// You can construct a concrete instance of `SyntheticsCreateBrowserCheckMapInput` via:
//
//	SyntheticsCreateBrowserCheckMap{ "key": SyntheticsCreateBrowserCheckArgs{...} }
type SyntheticsCreateBrowserCheckMapInput interface {
	pulumi.Input

	ToSyntheticsCreateBrowserCheckMapOutput() SyntheticsCreateBrowserCheckMapOutput
	ToSyntheticsCreateBrowserCheckMapOutputWithContext(context.Context) SyntheticsCreateBrowserCheckMapOutput
}

type SyntheticsCreateBrowserCheckMap map[string]SyntheticsCreateBrowserCheckInput

func (SyntheticsCreateBrowserCheckMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SyntheticsCreateBrowserCheck)(nil)).Elem()
}

func (i SyntheticsCreateBrowserCheckMap) ToSyntheticsCreateBrowserCheckMapOutput() SyntheticsCreateBrowserCheckMapOutput {
	return i.ToSyntheticsCreateBrowserCheckMapOutputWithContext(context.Background())
}

func (i SyntheticsCreateBrowserCheckMap) ToSyntheticsCreateBrowserCheckMapOutputWithContext(ctx context.Context) SyntheticsCreateBrowserCheckMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SyntheticsCreateBrowserCheckMapOutput)
}

type SyntheticsCreateBrowserCheckOutput struct{ *pulumi.OutputState }

func (SyntheticsCreateBrowserCheckOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SyntheticsCreateBrowserCheck)(nil)).Elem()
}

func (o SyntheticsCreateBrowserCheckOutput) ToSyntheticsCreateBrowserCheckOutput() SyntheticsCreateBrowserCheckOutput {
	return o
}

func (o SyntheticsCreateBrowserCheckOutput) ToSyntheticsCreateBrowserCheckOutputWithContext(ctx context.Context) SyntheticsCreateBrowserCheckOutput {
	return o
}

func (o SyntheticsCreateBrowserCheckOutput) AutoRetry() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.BoolPtrOutput { return v.AutoRetry }).(pulumi.BoolPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) AutoUpdateUserAgent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.BoolPtrOutput { return v.AutoUpdateUserAgent }).(pulumi.BoolPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) BlackoutPeriods() SyntheticsCreateBrowserCheckBlackoutPeriodArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckBlackoutPeriodArrayOutput {
		return v.BlackoutPeriods
	}).(SyntheticsCreateBrowserCheckBlackoutPeriodArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Browsers() SyntheticsCreateBrowserCheckBrowserArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckBrowserArrayOutput {
		return v.Browsers
	}).(SyntheticsCreateBrowserCheckBrowserArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) CheckConnections() SyntheticsCreateBrowserCheckCheckConnectionArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckCheckConnectionArrayOutput {
		return v.CheckConnections
	}).(SyntheticsCreateBrowserCheckCheckConnectionArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Cookies() SyntheticsCreateBrowserCheckCookieArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckCookieArrayOutput { return v.Cookies }).(SyntheticsCreateBrowserCheckCookieArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) DnsOverrides() SyntheticsCreateBrowserCheckDnsOverrideArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckDnsOverrideArrayOutput {
		return v.DnsOverrides
	}).(SyntheticsCreateBrowserCheckDnsOverrideArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) EnforceSslValidation() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.BoolPtrOutput { return v.EnforceSslValidation }).(pulumi.BoolPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) ExcludedFiles() SyntheticsCreateBrowserCheckExcludedFileArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckExcludedFileArrayOutput {
		return v.ExcludedFiles
	}).(SyntheticsCreateBrowserCheckExcludedFileArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Frequency() pulumi.IntOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.IntOutput { return v.Frequency }).(pulumi.IntOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) HttpMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringPtrOutput { return v.HttpMethod }).(pulumi.StringPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) HttpRequestBody() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringPtrOutput { return v.HttpRequestBody }).(pulumi.StringPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) HttpRequestHeaders() SyntheticsCreateBrowserCheckHttpRequestHeaderArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckHttpRequestHeaderArrayOutput {
		return v.HttpRequestHeaders
	}).(SyntheticsCreateBrowserCheckHttpRequestHeaderArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Integrations() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.IntArrayOutput { return v.Integrations }).(pulumi.IntArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) JavascriptFiles() SyntheticsCreateBrowserCheckJavascriptFileArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckJavascriptFileArrayOutput {
		return v.JavascriptFiles
	}).(SyntheticsCreateBrowserCheckJavascriptFileArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Locations() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.IntArrayOutput { return v.Locations }).(pulumi.IntArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Notifications() SyntheticsCreateBrowserCheckNotificationArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckNotificationArrayOutput {
		return v.Notifications
	}).(SyntheticsCreateBrowserCheckNotificationArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) RoundRobin() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.BoolPtrOutput { return v.RoundRobin }).(pulumi.BoolPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Steps() SyntheticsCreateBrowserCheckStepArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckStepArrayOutput { return v.Steps }).(SyntheticsCreateBrowserCheckStepArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) SuccessCriterias() SyntheticsCreateBrowserCheckSuccessCriteriaArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckSuccessCriteriaArrayOutput {
		return v.SuccessCriterias
	}).(SyntheticsCreateBrowserCheckSuccessCriteriaArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) ThresholdMonitors() SyntheticsCreateBrowserCheckThresholdMonitorArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckThresholdMonitorArrayOutput {
		return v.ThresholdMonitors
	}).(SyntheticsCreateBrowserCheckThresholdMonitorArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) UserAgent() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.StringPtrOutput { return v.UserAgent }).(pulumi.StringPtrOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) Viewports() SyntheticsCreateBrowserCheckViewportArrayOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) SyntheticsCreateBrowserCheckViewportArrayOutput {
		return v.Viewports
	}).(SyntheticsCreateBrowserCheckViewportArrayOutput)
}

func (o SyntheticsCreateBrowserCheckOutput) WaitForFullMetrics() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SyntheticsCreateBrowserCheck) pulumi.BoolPtrOutput { return v.WaitForFullMetrics }).(pulumi.BoolPtrOutput)
}

type SyntheticsCreateBrowserCheckArrayOutput struct{ *pulumi.OutputState }

func (SyntheticsCreateBrowserCheckArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SyntheticsCreateBrowserCheck)(nil)).Elem()
}

func (o SyntheticsCreateBrowserCheckArrayOutput) ToSyntheticsCreateBrowserCheckArrayOutput() SyntheticsCreateBrowserCheckArrayOutput {
	return o
}

func (o SyntheticsCreateBrowserCheckArrayOutput) ToSyntheticsCreateBrowserCheckArrayOutputWithContext(ctx context.Context) SyntheticsCreateBrowserCheckArrayOutput {
	return o
}

func (o SyntheticsCreateBrowserCheckArrayOutput) Index(i pulumi.IntInput) SyntheticsCreateBrowserCheckOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SyntheticsCreateBrowserCheck {
		return vs[0].([]*SyntheticsCreateBrowserCheck)[vs[1].(int)]
	}).(SyntheticsCreateBrowserCheckOutput)
}

type SyntheticsCreateBrowserCheckMapOutput struct{ *pulumi.OutputState }

func (SyntheticsCreateBrowserCheckMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SyntheticsCreateBrowserCheck)(nil)).Elem()
}

func (o SyntheticsCreateBrowserCheckMapOutput) ToSyntheticsCreateBrowserCheckMapOutput() SyntheticsCreateBrowserCheckMapOutput {
	return o
}

func (o SyntheticsCreateBrowserCheckMapOutput) ToSyntheticsCreateBrowserCheckMapOutputWithContext(ctx context.Context) SyntheticsCreateBrowserCheckMapOutput {
	return o
}

func (o SyntheticsCreateBrowserCheckMapOutput) MapIndex(k pulumi.StringInput) SyntheticsCreateBrowserCheckOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SyntheticsCreateBrowserCheck {
		return vs[0].(map[string]*SyntheticsCreateBrowserCheck)[vs[1].(string)]
	}).(SyntheticsCreateBrowserCheckOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SyntheticsCreateBrowserCheckInput)(nil)).Elem(), &SyntheticsCreateBrowserCheck{})
	pulumi.RegisterInputType(reflect.TypeOf((*SyntheticsCreateBrowserCheckArrayInput)(nil)).Elem(), SyntheticsCreateBrowserCheckArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SyntheticsCreateBrowserCheckMapInput)(nil)).Elem(), SyntheticsCreateBrowserCheckMap{})
	pulumi.RegisterOutputType(SyntheticsCreateBrowserCheckOutput{})
	pulumi.RegisterOutputType(SyntheticsCreateBrowserCheckArrayOutput{})
	pulumi.RegisterOutputType(SyntheticsCreateBrowserCheckMapOutput{})
}
