// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package synthetics

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yuft/pulumi-signalfx-synthetics/sdk/go/synthetics/internal"
)

// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/yuft/pulumi-signalfx-synthetics/sdk/go/synthetics"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := synthetics.SyntheticsLocationV2Check(ctx, &synthetics.SyntheticsLocationV2CheckArgs{
//				Locations: []synthetics.SyntheticsLocationV2CheckLocation{
//					{
//						Id: "private-aws-awesome-east",
//					},
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func SyntheticsLocationV2Check(ctx *pulumi.Context, args *SyntheticsLocationV2CheckArgs, opts ...pulumi.InvokeOption) (*SyntheticsLocationV2CheckResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv SyntheticsLocationV2CheckResult
	err := ctx.Invoke("synthetics:index/syntheticsLocationV2Check:syntheticsLocationV2Check", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking syntheticsLocationV2Check.
type SyntheticsLocationV2CheckArgs struct {
	Locations []SyntheticsLocationV2CheckLocation `pulumi:"locations"`
	Metas     []SyntheticsLocationV2CheckMeta     `pulumi:"metas"`
}

// A collection of values returned by syntheticsLocationV2Check.
type SyntheticsLocationV2CheckResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id        string                              `pulumi:"id"`
	Locations []SyntheticsLocationV2CheckLocation `pulumi:"locations"`
	Metas     []SyntheticsLocationV2CheckMeta     `pulumi:"metas"`
}

func SyntheticsLocationV2CheckOutput(ctx *pulumi.Context, args SyntheticsLocationV2CheckOutputArgs, opts ...pulumi.InvokeOption) SyntheticsLocationV2CheckResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (SyntheticsLocationV2CheckResult, error) {
			args := v.(SyntheticsLocationV2CheckArgs)
			r, err := SyntheticsLocationV2Check(ctx, &args, opts...)
			var s SyntheticsLocationV2CheckResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(SyntheticsLocationV2CheckResultOutput)
}

// A collection of arguments for invoking syntheticsLocationV2Check.
type SyntheticsLocationV2CheckOutputArgs struct {
	Locations SyntheticsLocationV2CheckLocationArrayInput `pulumi:"locations"`
	Metas     SyntheticsLocationV2CheckMetaArrayInput     `pulumi:"metas"`
}

func (SyntheticsLocationV2CheckOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SyntheticsLocationV2CheckArgs)(nil)).Elem()
}

// A collection of values returned by syntheticsLocationV2Check.
type SyntheticsLocationV2CheckResultOutput struct{ *pulumi.OutputState }

func (SyntheticsLocationV2CheckResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SyntheticsLocationV2CheckResult)(nil)).Elem()
}

func (o SyntheticsLocationV2CheckResultOutput) ToSyntheticsLocationV2CheckResultOutput() SyntheticsLocationV2CheckResultOutput {
	return o
}

func (o SyntheticsLocationV2CheckResultOutput) ToSyntheticsLocationV2CheckResultOutputWithContext(ctx context.Context) SyntheticsLocationV2CheckResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o SyntheticsLocationV2CheckResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v SyntheticsLocationV2CheckResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o SyntheticsLocationV2CheckResultOutput) Locations() SyntheticsLocationV2CheckLocationArrayOutput {
	return o.ApplyT(func(v SyntheticsLocationV2CheckResult) []SyntheticsLocationV2CheckLocation { return v.Locations }).(SyntheticsLocationV2CheckLocationArrayOutput)
}

func (o SyntheticsLocationV2CheckResultOutput) Metas() SyntheticsLocationV2CheckMetaArrayOutput {
	return o.ApplyT(func(v SyntheticsLocationV2CheckResult) []SyntheticsLocationV2CheckMeta { return v.Metas }).(SyntheticsLocationV2CheckMetaArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(SyntheticsLocationV2CheckResultOutput{})
}
