// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// &lt;!--Start PulumiCodeChooser --&gt;
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Synthetics = Pulumi.Synthetics;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var apiV2FooCheck = new Synthetics.SyntheticsCreateApiCheckV2("apiV2FooCheck", new()
    ///     {
    ///         Tests = new[]
    ///         {
    ///             new Synthetics.Inputs.SyntheticsCreateApiCheckV2TestArgs
    ///             {
    ///                 Active = true,
    ///                 DeviceId = 1,
    ///                 Frequency = 5,
    ///                 LocationIds = new[]
    ///                 {
    ///                     "aws-us-east-1",
    ///                 },
    ///                 Name = "Terraform - Api V2 Checkaroo",
    ///                 SchedulingStrategy = "round_robin",
    ///                 Requests = new[]
    ///                 {
    ///                     new Synthetics.Inputs.SyntheticsCreateApiCheckV2TestRequestArgs
    ///                     {
    ///                         Configurations = new[]
    ///                         {
    ///                             new Synthetics.Inputs.SyntheticsCreateApiCheckV2TestRequestConfigurationArgs
    ///                             {
    ///                                 Body = @"\'{""alert_name"":""the service is down"",""url"":""https://foo.com/bar""}\'
    /// ",
    ///                                 Headers = 
    ///                                 {
    ///                                     { "Accept", "application/json" },
    ///                                     { "x-foo", "bar" },
    ///                                 },
    ///                                 Name = "Get products",
    ///                                 RequestMethod = "GET",
    ///                                 Url = "https://dummyjson.com/products",
    ///                             },
    ///                         },
    ///                         Setups = new[]
    ///                         {
    ///                             new Synthetics.Inputs.SyntheticsCreateApiCheckV2TestRequestSetupArgs
    ///                             {
    ///                                 Extractor = "$.foo",
    ///                                 Name = "First setup step",
    ///                                 Source = "{\\'foo\\': \\'bar\\'}",
    ///                                 Type = "extract_json",
    ///                                 Variable = "myVariable",
    ///                             },
    ///                         },
    ///                         Validations = new[]
    ///                         {
    ///                             new Synthetics.Inputs.SyntheticsCreateApiCheckV2TestRequestValidationArgs
    ///                             {
    ///                                 Actual = "{{response.code}}",
    ///                                 Comparator = "equals",
    ///                                 Expected = "200",
    ///                                 Name = "My validation step",
    ///                                 Type = "assert_numeric",
    ///                             },
    ///                         },
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// &lt;!--End PulumiCodeChooser --&gt;
    /// </summary>
    [SyntheticsResourceType("synthetics:index/syntheticsCreateApiCheckV2:SyntheticsCreateApiCheckV2")]
    public partial class SyntheticsCreateApiCheckV2 : global::Pulumi.CustomResource
    {
        [Output("tests")]
        public Output<ImmutableArray<Outputs.SyntheticsCreateApiCheckV2Test>> Tests { get; private set; } = null!;


        /// <summary>
        /// Create a SyntheticsCreateApiCheckV2 resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SyntheticsCreateApiCheckV2(string name, SyntheticsCreateApiCheckV2Args args, CustomResourceOptions? options = null)
            : base("synthetics:index/syntheticsCreateApiCheckV2:SyntheticsCreateApiCheckV2", name, args ?? new SyntheticsCreateApiCheckV2Args(), MakeResourceOptions(options, ""))
        {
        }

        private SyntheticsCreateApiCheckV2(string name, Input<string> id, SyntheticsCreateApiCheckV2State? state = null, CustomResourceOptions? options = null)
            : base("synthetics:index/syntheticsCreateApiCheckV2:SyntheticsCreateApiCheckV2", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SyntheticsCreateApiCheckV2 resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SyntheticsCreateApiCheckV2 Get(string name, Input<string> id, SyntheticsCreateApiCheckV2State? state = null, CustomResourceOptions? options = null)
        {
            return new SyntheticsCreateApiCheckV2(name, id, state, options);
        }
    }

    public sealed class SyntheticsCreateApiCheckV2Args : global::Pulumi.ResourceArgs
    {
        [Input("tests", required: true)]
        private InputList<Inputs.SyntheticsCreateApiCheckV2TestArgs>? _tests;
        public InputList<Inputs.SyntheticsCreateApiCheckV2TestArgs> Tests
        {
            get => _tests ?? (_tests = new InputList<Inputs.SyntheticsCreateApiCheckV2TestArgs>());
            set => _tests = value;
        }

        public SyntheticsCreateApiCheckV2Args()
        {
        }
        public static new SyntheticsCreateApiCheckV2Args Empty => new SyntheticsCreateApiCheckV2Args();
    }

    public sealed class SyntheticsCreateApiCheckV2State : global::Pulumi.ResourceArgs
    {
        [Input("tests")]
        private InputList<Inputs.SyntheticsCreateApiCheckV2TestGetArgs>? _tests;
        public InputList<Inputs.SyntheticsCreateApiCheckV2TestGetArgs> Tests
        {
            get => _tests ?? (_tests = new InputList<Inputs.SyntheticsCreateApiCheckV2TestGetArgs>());
            set => _tests = value;
        }

        public SyntheticsCreateApiCheckV2State()
        {
        }
        public static new SyntheticsCreateApiCheckV2State Empty => new SyntheticsCreateApiCheckV2State();
    }
}
