# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SyntheticsCreateBrowserCheckArgs', 'SyntheticsCreateBrowserCheck']

@pulumi.input_type
class SyntheticsCreateBrowserCheckArgs:
    def __init__(__self__, *,
                 frequency: pulumi.Input[int],
                 url: pulumi.Input[str],
                 auto_retry: Optional[pulumi.Input[bool]] = None,
                 auto_update_user_agent: Optional[pulumi.Input[bool]] = None,
                 blackout_periods: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]] = None,
                 browsers: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBrowserArgs']]]] = None,
                 check_connections: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]] = None,
                 cookies: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCookieArgs']]]] = None,
                 dns_overrides: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 enforce_ssl_validation: Optional[pulumi.Input[bool]] = None,
                 excluded_files: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckExcludedFileArgs']]]] = None,
                 http_method: Optional[pulumi.Input[str]] = None,
                 http_request_body: Optional[pulumi.Input[str]] = None,
                 http_request_headers: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]] = None,
                 integrations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 javascript_files: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]] = None,
                 last_updated: Optional[pulumi.Input[str]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 notifications: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckNotificationArgs']]]] = None,
                 round_robin: Optional[pulumi.Input[bool]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckStepArgs']]]] = None,
                 success_criterias: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 threshold_monitors: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 user_agent: Optional[pulumi.Input[str]] = None,
                 viewports: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckViewportArgs']]]] = None,
                 wait_for_full_metrics: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a SyntheticsCreateBrowserCheck resource.
        """
        pulumi.set(__self__, "frequency", frequency)
        pulumi.set(__self__, "url", url)
        if auto_retry is not None:
            pulumi.set(__self__, "auto_retry", auto_retry)
        if auto_update_user_agent is not None:
            pulumi.set(__self__, "auto_update_user_agent", auto_update_user_agent)
        if blackout_periods is not None:
            pulumi.set(__self__, "blackout_periods", blackout_periods)
        if browsers is not None:
            pulumi.set(__self__, "browsers", browsers)
        if check_connections is not None:
            pulumi.set(__self__, "check_connections", check_connections)
        if cookies is not None:
            pulumi.set(__self__, "cookies", cookies)
        if dns_overrides is not None:
            pulumi.set(__self__, "dns_overrides", dns_overrides)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if enforce_ssl_validation is not None:
            pulumi.set(__self__, "enforce_ssl_validation", enforce_ssl_validation)
        if excluded_files is not None:
            pulumi.set(__self__, "excluded_files", excluded_files)
        if http_method is not None:
            pulumi.set(__self__, "http_method", http_method)
        if http_request_body is not None:
            pulumi.set(__self__, "http_request_body", http_request_body)
        if http_request_headers is not None:
            pulumi.set(__self__, "http_request_headers", http_request_headers)
        if integrations is not None:
            pulumi.set(__self__, "integrations", integrations)
        if javascript_files is not None:
            pulumi.set(__self__, "javascript_files", javascript_files)
        if last_updated is not None:
            pulumi.set(__self__, "last_updated", last_updated)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notifications is not None:
            pulumi.set(__self__, "notifications", notifications)
        if round_robin is not None:
            pulumi.set(__self__, "round_robin", round_robin)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)
        if success_criterias is not None:
            pulumi.set(__self__, "success_criterias", success_criterias)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if threshold_monitors is not None:
            pulumi.set(__self__, "threshold_monitors", threshold_monitors)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if user_agent is not None:
            pulumi.set(__self__, "user_agent", user_agent)
        if viewports is not None:
            pulumi.set(__self__, "viewports", viewports)
        if wait_for_full_metrics is not None:
            pulumi.set(__self__, "wait_for_full_metrics", wait_for_full_metrics)

    @property
    @pulumi.getter
    def frequency(self) -> pulumi.Input[int]:
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: pulumi.Input[int]):
        pulumi.set(self, "frequency", value)

    @property
    @pulumi.getter
    def url(self) -> pulumi.Input[str]:
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[str]):
        pulumi.set(self, "url", value)

    @property
    @pulumi.getter(name="autoRetry")
    def auto_retry(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "auto_retry")

    @auto_retry.setter
    def auto_retry(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "auto_retry", value)

    @property
    @pulumi.getter(name="autoUpdateUserAgent")
    def auto_update_user_agent(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "auto_update_user_agent")

    @auto_update_user_agent.setter
    def auto_update_user_agent(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "auto_update_user_agent", value)

    @property
    @pulumi.getter(name="blackoutPeriods")
    def blackout_periods(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]]:
        return pulumi.get(self, "blackout_periods")

    @blackout_periods.setter
    def blackout_periods(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]]):
        pulumi.set(self, "blackout_periods", value)

    @property
    @pulumi.getter
    def browsers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBrowserArgs']]]]:
        return pulumi.get(self, "browsers")

    @browsers.setter
    def browsers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBrowserArgs']]]]):
        pulumi.set(self, "browsers", value)

    @property
    @pulumi.getter(name="checkConnections")
    def check_connections(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]]:
        return pulumi.get(self, "check_connections")

    @check_connections.setter
    def check_connections(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]]):
        pulumi.set(self, "check_connections", value)

    @property
    @pulumi.getter
    def cookies(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCookieArgs']]]]:
        return pulumi.get(self, "cookies")

    @cookies.setter
    def cookies(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCookieArgs']]]]):
        pulumi.set(self, "cookies", value)

    @property
    @pulumi.getter(name="dnsOverrides")
    def dns_overrides(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]]:
        return pulumi.get(self, "dns_overrides")

    @dns_overrides.setter
    def dns_overrides(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]]):
        pulumi.set(self, "dns_overrides", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="enforceSslValidation")
    def enforce_ssl_validation(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "enforce_ssl_validation")

    @enforce_ssl_validation.setter
    def enforce_ssl_validation(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enforce_ssl_validation", value)

    @property
    @pulumi.getter(name="excludedFiles")
    def excluded_files(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckExcludedFileArgs']]]]:
        return pulumi.get(self, "excluded_files")

    @excluded_files.setter
    def excluded_files(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckExcludedFileArgs']]]]):
        pulumi.set(self, "excluded_files", value)

    @property
    @pulumi.getter(name="httpMethod")
    def http_method(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "http_method")

    @http_method.setter
    def http_method(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "http_method", value)

    @property
    @pulumi.getter(name="httpRequestBody")
    def http_request_body(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "http_request_body")

    @http_request_body.setter
    def http_request_body(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "http_request_body", value)

    @property
    @pulumi.getter(name="httpRequestHeaders")
    def http_request_headers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]]:
        return pulumi.get(self, "http_request_headers")

    @http_request_headers.setter
    def http_request_headers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]]):
        pulumi.set(self, "http_request_headers", value)

    @property
    @pulumi.getter
    def integrations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        return pulumi.get(self, "integrations")

    @integrations.setter
    def integrations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "integrations", value)

    @property
    @pulumi.getter(name="javascriptFiles")
    def javascript_files(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]]:
        return pulumi.get(self, "javascript_files")

    @javascript_files.setter
    def javascript_files(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]]):
        pulumi.set(self, "javascript_files", value)

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "last_updated")

    @last_updated.setter
    def last_updated(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "last_updated", value)

    @property
    @pulumi.getter
    def locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        return pulumi.get(self, "locations")

    @locations.setter
    def locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "locations", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def notifications(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckNotificationArgs']]]]:
        return pulumi.get(self, "notifications")

    @notifications.setter
    def notifications(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckNotificationArgs']]]]):
        pulumi.set(self, "notifications", value)

    @property
    @pulumi.getter(name="roundRobin")
    def round_robin(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "round_robin")

    @round_robin.setter
    def round_robin(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "round_robin", value)

    @property
    @pulumi.getter
    def steps(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckStepArgs']]]]:
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckStepArgs']]]]):
        pulumi.set(self, "steps", value)

    @property
    @pulumi.getter(name="successCriterias")
    def success_criterias(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]]:
        return pulumi.get(self, "success_criterias")

    @success_criterias.setter
    def success_criterias(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]]):
        pulumi.set(self, "success_criterias", value)

    @property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "tags", value)

    @property
    @pulumi.getter(name="thresholdMonitors")
    def threshold_monitors(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]]:
        return pulumi.get(self, "threshold_monitors")

    @threshold_monitors.setter
    def threshold_monitors(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]]):
        pulumi.set(self, "threshold_monitors", value)

    @property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter(name="userAgent")
    def user_agent(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "user_agent")

    @user_agent.setter
    def user_agent(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "user_agent", value)

    @property
    @pulumi.getter
    def viewports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckViewportArgs']]]]:
        return pulumi.get(self, "viewports")

    @viewports.setter
    def viewports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckViewportArgs']]]]):
        pulumi.set(self, "viewports", value)

    @property
    @pulumi.getter(name="waitForFullMetrics")
    def wait_for_full_metrics(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "wait_for_full_metrics")

    @wait_for_full_metrics.setter
    def wait_for_full_metrics(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "wait_for_full_metrics", value)


@pulumi.input_type
class _SyntheticsCreateBrowserCheckState:
    def __init__(__self__, *,
                 auto_retry: Optional[pulumi.Input[bool]] = None,
                 auto_update_user_agent: Optional[pulumi.Input[bool]] = None,
                 blackout_periods: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]] = None,
                 browsers: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBrowserArgs']]]] = None,
                 check_connections: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]] = None,
                 cookies: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCookieArgs']]]] = None,
                 dns_overrides: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 enforce_ssl_validation: Optional[pulumi.Input[bool]] = None,
                 excluded_files: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckExcludedFileArgs']]]] = None,
                 frequency: Optional[pulumi.Input[int]] = None,
                 http_method: Optional[pulumi.Input[str]] = None,
                 http_request_body: Optional[pulumi.Input[str]] = None,
                 http_request_headers: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]] = None,
                 integrations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 javascript_files: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]] = None,
                 last_updated: Optional[pulumi.Input[str]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 notifications: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckNotificationArgs']]]] = None,
                 round_robin: Optional[pulumi.Input[bool]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckStepArgs']]]] = None,
                 success_criterias: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 threshold_monitors: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 user_agent: Optional[pulumi.Input[str]] = None,
                 viewports: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckViewportArgs']]]] = None,
                 wait_for_full_metrics: Optional[pulumi.Input[bool]] = None):
        """
        Input properties used for looking up and filtering SyntheticsCreateBrowserCheck resources.
        """
        if auto_retry is not None:
            pulumi.set(__self__, "auto_retry", auto_retry)
        if auto_update_user_agent is not None:
            pulumi.set(__self__, "auto_update_user_agent", auto_update_user_agent)
        if blackout_periods is not None:
            pulumi.set(__self__, "blackout_periods", blackout_periods)
        if browsers is not None:
            pulumi.set(__self__, "browsers", browsers)
        if check_connections is not None:
            pulumi.set(__self__, "check_connections", check_connections)
        if cookies is not None:
            pulumi.set(__self__, "cookies", cookies)
        if dns_overrides is not None:
            pulumi.set(__self__, "dns_overrides", dns_overrides)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if enforce_ssl_validation is not None:
            pulumi.set(__self__, "enforce_ssl_validation", enforce_ssl_validation)
        if excluded_files is not None:
            pulumi.set(__self__, "excluded_files", excluded_files)
        if frequency is not None:
            pulumi.set(__self__, "frequency", frequency)
        if http_method is not None:
            pulumi.set(__self__, "http_method", http_method)
        if http_request_body is not None:
            pulumi.set(__self__, "http_request_body", http_request_body)
        if http_request_headers is not None:
            pulumi.set(__self__, "http_request_headers", http_request_headers)
        if integrations is not None:
            pulumi.set(__self__, "integrations", integrations)
        if javascript_files is not None:
            pulumi.set(__self__, "javascript_files", javascript_files)
        if last_updated is not None:
            pulumi.set(__self__, "last_updated", last_updated)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notifications is not None:
            pulumi.set(__self__, "notifications", notifications)
        if round_robin is not None:
            pulumi.set(__self__, "round_robin", round_robin)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)
        if success_criterias is not None:
            pulumi.set(__self__, "success_criterias", success_criterias)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if threshold_monitors is not None:
            pulumi.set(__self__, "threshold_monitors", threshold_monitors)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if user_agent is not None:
            pulumi.set(__self__, "user_agent", user_agent)
        if viewports is not None:
            pulumi.set(__self__, "viewports", viewports)
        if wait_for_full_metrics is not None:
            pulumi.set(__self__, "wait_for_full_metrics", wait_for_full_metrics)

    @property
    @pulumi.getter(name="autoRetry")
    def auto_retry(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "auto_retry")

    @auto_retry.setter
    def auto_retry(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "auto_retry", value)

    @property
    @pulumi.getter(name="autoUpdateUserAgent")
    def auto_update_user_agent(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "auto_update_user_agent")

    @auto_update_user_agent.setter
    def auto_update_user_agent(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "auto_update_user_agent", value)

    @property
    @pulumi.getter(name="blackoutPeriods")
    def blackout_periods(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]]:
        return pulumi.get(self, "blackout_periods")

    @blackout_periods.setter
    def blackout_periods(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]]):
        pulumi.set(self, "blackout_periods", value)

    @property
    @pulumi.getter
    def browsers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBrowserArgs']]]]:
        return pulumi.get(self, "browsers")

    @browsers.setter
    def browsers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckBrowserArgs']]]]):
        pulumi.set(self, "browsers", value)

    @property
    @pulumi.getter(name="checkConnections")
    def check_connections(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]]:
        return pulumi.get(self, "check_connections")

    @check_connections.setter
    def check_connections(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]]):
        pulumi.set(self, "check_connections", value)

    @property
    @pulumi.getter
    def cookies(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCookieArgs']]]]:
        return pulumi.get(self, "cookies")

    @cookies.setter
    def cookies(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckCookieArgs']]]]):
        pulumi.set(self, "cookies", value)

    @property
    @pulumi.getter(name="dnsOverrides")
    def dns_overrides(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]]:
        return pulumi.get(self, "dns_overrides")

    @dns_overrides.setter
    def dns_overrides(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]]):
        pulumi.set(self, "dns_overrides", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="enforceSslValidation")
    def enforce_ssl_validation(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "enforce_ssl_validation")

    @enforce_ssl_validation.setter
    def enforce_ssl_validation(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enforce_ssl_validation", value)

    @property
    @pulumi.getter(name="excludedFiles")
    def excluded_files(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckExcludedFileArgs']]]]:
        return pulumi.get(self, "excluded_files")

    @excluded_files.setter
    def excluded_files(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckExcludedFileArgs']]]]):
        pulumi.set(self, "excluded_files", value)

    @property
    @pulumi.getter
    def frequency(self) -> Optional[pulumi.Input[int]]:
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "frequency", value)

    @property
    @pulumi.getter(name="httpMethod")
    def http_method(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "http_method")

    @http_method.setter
    def http_method(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "http_method", value)

    @property
    @pulumi.getter(name="httpRequestBody")
    def http_request_body(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "http_request_body")

    @http_request_body.setter
    def http_request_body(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "http_request_body", value)

    @property
    @pulumi.getter(name="httpRequestHeaders")
    def http_request_headers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]]:
        return pulumi.get(self, "http_request_headers")

    @http_request_headers.setter
    def http_request_headers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]]):
        pulumi.set(self, "http_request_headers", value)

    @property
    @pulumi.getter
    def integrations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        return pulumi.get(self, "integrations")

    @integrations.setter
    def integrations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "integrations", value)

    @property
    @pulumi.getter(name="javascriptFiles")
    def javascript_files(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]]:
        return pulumi.get(self, "javascript_files")

    @javascript_files.setter
    def javascript_files(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]]):
        pulumi.set(self, "javascript_files", value)

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "last_updated")

    @last_updated.setter
    def last_updated(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "last_updated", value)

    @property
    @pulumi.getter
    def locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        return pulumi.get(self, "locations")

    @locations.setter
    def locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "locations", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def notifications(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckNotificationArgs']]]]:
        return pulumi.get(self, "notifications")

    @notifications.setter
    def notifications(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckNotificationArgs']]]]):
        pulumi.set(self, "notifications", value)

    @property
    @pulumi.getter(name="roundRobin")
    def round_robin(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "round_robin")

    @round_robin.setter
    def round_robin(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "round_robin", value)

    @property
    @pulumi.getter
    def steps(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckStepArgs']]]]:
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckStepArgs']]]]):
        pulumi.set(self, "steps", value)

    @property
    @pulumi.getter(name="successCriterias")
    def success_criterias(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]]:
        return pulumi.get(self, "success_criterias")

    @success_criterias.setter
    def success_criterias(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]]):
        pulumi.set(self, "success_criterias", value)

    @property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "tags", value)

    @property
    @pulumi.getter(name="thresholdMonitors")
    def threshold_monitors(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]]:
        return pulumi.get(self, "threshold_monitors")

    @threshold_monitors.setter
    def threshold_monitors(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]]):
        pulumi.set(self, "threshold_monitors", value)

    @property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url", value)

    @property
    @pulumi.getter(name="userAgent")
    def user_agent(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "user_agent")

    @user_agent.setter
    def user_agent(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "user_agent", value)

    @property
    @pulumi.getter
    def viewports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckViewportArgs']]]]:
        return pulumi.get(self, "viewports")

    @viewports.setter
    def viewports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SyntheticsCreateBrowserCheckViewportArgs']]]]):
        pulumi.set(self, "viewports", value)

    @property
    @pulumi.getter(name="waitForFullMetrics")
    def wait_for_full_metrics(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "wait_for_full_metrics")

    @wait_for_full_metrics.setter
    def wait_for_full_metrics(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "wait_for_full_metrics", value)


class SyntheticsCreateBrowserCheck(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_retry: Optional[pulumi.Input[bool]] = None,
                 auto_update_user_agent: Optional[pulumi.Input[bool]] = None,
                 blackout_periods: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]]] = None,
                 browsers: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckBrowserArgs']]]]] = None,
                 check_connections: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]]] = None,
                 cookies: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckCookieArgs']]]]] = None,
                 dns_overrides: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 enforce_ssl_validation: Optional[pulumi.Input[bool]] = None,
                 excluded_files: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckExcludedFileArgs']]]]] = None,
                 frequency: Optional[pulumi.Input[int]] = None,
                 http_method: Optional[pulumi.Input[str]] = None,
                 http_request_body: Optional[pulumi.Input[str]] = None,
                 http_request_headers: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]]] = None,
                 integrations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 javascript_files: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]]] = None,
                 last_updated: Optional[pulumi.Input[str]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 notifications: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckNotificationArgs']]]]] = None,
                 round_robin: Optional[pulumi.Input[bool]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckStepArgs']]]]] = None,
                 success_criterias: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 threshold_monitors: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 user_agent: Optional[pulumi.Input[str]] = None,
                 viewports: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckViewportArgs']]]]] = None,
                 wait_for_full_metrics: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        """
        **Note**: This is a Rigor (Legacy) resource

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SyntheticsCreateBrowserCheckArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        **Note**: This is a Rigor (Legacy) resource

        :param str resource_name: The name of the resource.
        :param SyntheticsCreateBrowserCheckArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SyntheticsCreateBrowserCheckArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_retry: Optional[pulumi.Input[bool]] = None,
                 auto_update_user_agent: Optional[pulumi.Input[bool]] = None,
                 blackout_periods: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]]] = None,
                 browsers: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckBrowserArgs']]]]] = None,
                 check_connections: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]]] = None,
                 cookies: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckCookieArgs']]]]] = None,
                 dns_overrides: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 enforce_ssl_validation: Optional[pulumi.Input[bool]] = None,
                 excluded_files: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckExcludedFileArgs']]]]] = None,
                 frequency: Optional[pulumi.Input[int]] = None,
                 http_method: Optional[pulumi.Input[str]] = None,
                 http_request_body: Optional[pulumi.Input[str]] = None,
                 http_request_headers: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]]] = None,
                 integrations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 javascript_files: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]]] = None,
                 last_updated: Optional[pulumi.Input[str]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 notifications: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckNotificationArgs']]]]] = None,
                 round_robin: Optional[pulumi.Input[bool]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckStepArgs']]]]] = None,
                 success_criterias: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 threshold_monitors: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 user_agent: Optional[pulumi.Input[str]] = None,
                 viewports: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckViewportArgs']]]]] = None,
                 wait_for_full_metrics: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SyntheticsCreateBrowserCheckArgs.__new__(SyntheticsCreateBrowserCheckArgs)

            __props__.__dict__["auto_retry"] = auto_retry
            __props__.__dict__["auto_update_user_agent"] = auto_update_user_agent
            __props__.__dict__["blackout_periods"] = blackout_periods
            __props__.__dict__["browsers"] = browsers
            __props__.__dict__["check_connections"] = check_connections
            __props__.__dict__["cookies"] = cookies
            __props__.__dict__["dns_overrides"] = dns_overrides
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["enforce_ssl_validation"] = enforce_ssl_validation
            __props__.__dict__["excluded_files"] = excluded_files
            if frequency is None and not opts.urn:
                raise TypeError("Missing required property 'frequency'")
            __props__.__dict__["frequency"] = frequency
            __props__.__dict__["http_method"] = http_method
            __props__.__dict__["http_request_body"] = http_request_body
            __props__.__dict__["http_request_headers"] = http_request_headers
            __props__.__dict__["integrations"] = integrations
            __props__.__dict__["javascript_files"] = javascript_files
            __props__.__dict__["last_updated"] = last_updated
            __props__.__dict__["locations"] = locations
            __props__.__dict__["name"] = name
            __props__.__dict__["notifications"] = notifications
            __props__.__dict__["round_robin"] = round_robin
            __props__.__dict__["steps"] = steps
            __props__.__dict__["success_criterias"] = success_criterias
            __props__.__dict__["tags"] = tags
            __props__.__dict__["threshold_monitors"] = threshold_monitors
            __props__.__dict__["type"] = type
            if url is None and not opts.urn:
                raise TypeError("Missing required property 'url'")
            __props__.__dict__["url"] = url
            __props__.__dict__["user_agent"] = user_agent
            __props__.__dict__["viewports"] = viewports
            __props__.__dict__["wait_for_full_metrics"] = wait_for_full_metrics
        super(SyntheticsCreateBrowserCheck, __self__).__init__(
            'synthetics:index/syntheticsCreateBrowserCheck:SyntheticsCreateBrowserCheck',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auto_retry: Optional[pulumi.Input[bool]] = None,
            auto_update_user_agent: Optional[pulumi.Input[bool]] = None,
            blackout_periods: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckBlackoutPeriodArgs']]]]] = None,
            browsers: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckBrowserArgs']]]]] = None,
            check_connections: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckCheckConnectionArgs']]]]] = None,
            cookies: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckCookieArgs']]]]] = None,
            dns_overrides: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckDnsOverrideArgs']]]]] = None,
            enabled: Optional[pulumi.Input[bool]] = None,
            enforce_ssl_validation: Optional[pulumi.Input[bool]] = None,
            excluded_files: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckExcludedFileArgs']]]]] = None,
            frequency: Optional[pulumi.Input[int]] = None,
            http_method: Optional[pulumi.Input[str]] = None,
            http_request_body: Optional[pulumi.Input[str]] = None,
            http_request_headers: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckHttpRequestHeaderArgs']]]]] = None,
            integrations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
            javascript_files: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckJavascriptFileArgs']]]]] = None,
            last_updated: Optional[pulumi.Input[str]] = None,
            locations: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
            name: Optional[pulumi.Input[str]] = None,
            notifications: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckNotificationArgs']]]]] = None,
            round_robin: Optional[pulumi.Input[bool]] = None,
            steps: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckStepArgs']]]]] = None,
            success_criterias: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckSuccessCriteriaArgs']]]]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            threshold_monitors: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckThresholdMonitorArgs']]]]] = None,
            type: Optional[pulumi.Input[str]] = None,
            url: Optional[pulumi.Input[str]] = None,
            user_agent: Optional[pulumi.Input[str]] = None,
            viewports: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['SyntheticsCreateBrowserCheckViewportArgs']]]]] = None,
            wait_for_full_metrics: Optional[pulumi.Input[bool]] = None) -> 'SyntheticsCreateBrowserCheck':
        """
        Get an existing SyntheticsCreateBrowserCheck resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SyntheticsCreateBrowserCheckState.__new__(_SyntheticsCreateBrowserCheckState)

        __props__.__dict__["auto_retry"] = auto_retry
        __props__.__dict__["auto_update_user_agent"] = auto_update_user_agent
        __props__.__dict__["blackout_periods"] = blackout_periods
        __props__.__dict__["browsers"] = browsers
        __props__.__dict__["check_connections"] = check_connections
        __props__.__dict__["cookies"] = cookies
        __props__.__dict__["dns_overrides"] = dns_overrides
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["enforce_ssl_validation"] = enforce_ssl_validation
        __props__.__dict__["excluded_files"] = excluded_files
        __props__.__dict__["frequency"] = frequency
        __props__.__dict__["http_method"] = http_method
        __props__.__dict__["http_request_body"] = http_request_body
        __props__.__dict__["http_request_headers"] = http_request_headers
        __props__.__dict__["integrations"] = integrations
        __props__.__dict__["javascript_files"] = javascript_files
        __props__.__dict__["last_updated"] = last_updated
        __props__.__dict__["locations"] = locations
        __props__.__dict__["name"] = name
        __props__.__dict__["notifications"] = notifications
        __props__.__dict__["round_robin"] = round_robin
        __props__.__dict__["steps"] = steps
        __props__.__dict__["success_criterias"] = success_criterias
        __props__.__dict__["tags"] = tags
        __props__.__dict__["threshold_monitors"] = threshold_monitors
        __props__.__dict__["type"] = type
        __props__.__dict__["url"] = url
        __props__.__dict__["user_agent"] = user_agent
        __props__.__dict__["viewports"] = viewports
        __props__.__dict__["wait_for_full_metrics"] = wait_for_full_metrics
        return SyntheticsCreateBrowserCheck(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="autoRetry")
    def auto_retry(self) -> pulumi.Output[Optional[bool]]:
        return pulumi.get(self, "auto_retry")

    @property
    @pulumi.getter(name="autoUpdateUserAgent")
    def auto_update_user_agent(self) -> pulumi.Output[Optional[bool]]:
        return pulumi.get(self, "auto_update_user_agent")

    @property
    @pulumi.getter(name="blackoutPeriods")
    def blackout_periods(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckBlackoutPeriod']]]:
        return pulumi.get(self, "blackout_periods")

    @property
    @pulumi.getter
    def browsers(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckBrowser']]]:
        return pulumi.get(self, "browsers")

    @property
    @pulumi.getter(name="checkConnections")
    def check_connections(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckCheckConnection']]]:
        return pulumi.get(self, "check_connections")

    @property
    @pulumi.getter
    def cookies(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckCookie']]]:
        return pulumi.get(self, "cookies")

    @property
    @pulumi.getter(name="dnsOverrides")
    def dns_overrides(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckDnsOverride']]]:
        return pulumi.get(self, "dns_overrides")

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[bool]]:
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter(name="enforceSslValidation")
    def enforce_ssl_validation(self) -> pulumi.Output[Optional[bool]]:
        return pulumi.get(self, "enforce_ssl_validation")

    @property
    @pulumi.getter(name="excludedFiles")
    def excluded_files(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckExcludedFile']]]:
        return pulumi.get(self, "excluded_files")

    @property
    @pulumi.getter
    def frequency(self) -> pulumi.Output[int]:
        return pulumi.get(self, "frequency")

    @property
    @pulumi.getter(name="httpMethod")
    def http_method(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "http_method")

    @property
    @pulumi.getter(name="httpRequestBody")
    def http_request_body(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "http_request_body")

    @property
    @pulumi.getter(name="httpRequestHeaders")
    def http_request_headers(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckHttpRequestHeader']]]:
        return pulumi.get(self, "http_request_headers")

    @property
    @pulumi.getter
    def integrations(self) -> pulumi.Output[Optional[Sequence[int]]]:
        return pulumi.get(self, "integrations")

    @property
    @pulumi.getter(name="javascriptFiles")
    def javascript_files(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckJavascriptFile']]]:
        return pulumi.get(self, "javascript_files")

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> pulumi.Output[str]:
        return pulumi.get(self, "last_updated")

    @property
    @pulumi.getter
    def locations(self) -> pulumi.Output[Optional[Sequence[int]]]:
        return pulumi.get(self, "locations")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def notifications(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckNotification']]]:
        return pulumi.get(self, "notifications")

    @property
    @pulumi.getter(name="roundRobin")
    def round_robin(self) -> pulumi.Output[Optional[bool]]:
        return pulumi.get(self, "round_robin")

    @property
    @pulumi.getter
    def steps(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckStep']]]:
        return pulumi.get(self, "steps")

    @property
    @pulumi.getter(name="successCriterias")
    def success_criterias(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckSuccessCriteria']]]:
        return pulumi.get(self, "success_criterias")

    @property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[str]]]:
        return pulumi.get(self, "tags")

    @property
    @pulumi.getter(name="thresholdMonitors")
    def threshold_monitors(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckThresholdMonitor']]]:
        return pulumi.get(self, "threshold_monitors")

    @property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def url(self) -> pulumi.Output[str]:
        return pulumi.get(self, "url")

    @property
    @pulumi.getter(name="userAgent")
    def user_agent(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "user_agent")

    @property
    @pulumi.getter
    def viewports(self) -> pulumi.Output[Optional[Sequence['outputs.SyntheticsCreateBrowserCheckViewport']]]:
        return pulumi.get(self, "viewports")

    @property
    @pulumi.getter(name="waitForFullMetrics")
    def wait_for_full_metrics(self) -> pulumi.Output[Optional[bool]]:
        return pulumi.get(self, "wait_for_full_metrics")

