# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apikey: Optional[str]
"""
Splunk Observability API Key. Will pull from `OBSERVABILITY_API_TOKEN` environment variable if available.
"""

product: Optional[str]
"""
One of: `observability` or `rigor`
"""

realm: Optional[str]
"""
Splunk Observability Realm (E.G. `us1`). Will pull from `REALM` environment variable if available. For Rigor use realm
rigor
"""

