// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCreateBrowserCheckExcludedFile
    {
        public readonly string? ExclusionType;
        public readonly string? Pattern;
        public readonly string? PresetName;

        [OutputConstructor]
        private SyntheticsCreateBrowserCheckExcludedFile(
            string? exclusionType,

            string? pattern,

            string? presetName)
        {
            ExclusionType = exclusionType;
            Pattern = pattern;
            PresetName = presetName;
        }
    }
}
