// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsDevicesV2CheckDeviceResult
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int Id;
        public readonly string Label;
        public readonly ImmutableArray<Outputs.SyntheticsDevicesV2CheckDeviceNetworkConnectionResult> NetworkConnections;
        public readonly string UserAgent;
        public readonly int ViewportHeight;
        public readonly int ViewportWidth;

        [OutputConstructor]
        private SyntheticsDevicesV2CheckDeviceResult(
            int id,

            string label,

            ImmutableArray<Outputs.SyntheticsDevicesV2CheckDeviceNetworkConnectionResult> networkConnections,

            string userAgent,

            int viewportHeight,

            int viewportWidth)
        {
            Id = id;
            Label = label;
            NetworkConnections = networkConnections;
            UserAgent = userAgent;
            ViewportHeight = viewportHeight;
            ViewportWidth = viewportWidth;
        }
    }
}
