// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsApiV2CheckTestResult
    {
        public readonly bool Active;
        public readonly string CreatedAt;
        public readonly ImmutableArray<Outputs.SyntheticsApiV2CheckTestDeviceResult> Devices;
        public readonly int Frequency;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int Id;
        public readonly ImmutableArray<string> LocationIds;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestResult> Requests;
        public readonly string SchedulingStrategy;
        public readonly string Type;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private SyntheticsApiV2CheckTestResult(
            bool active,

            string createdAt,

            ImmutableArray<Outputs.SyntheticsApiV2CheckTestDeviceResult> devices,

            int frequency,

            int id,

            ImmutableArray<string> locationIds,

            string name,

            ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestResult> requests,

            string schedulingStrategy,

            string type,

            string updatedAt)
        {
            Active = active;
            CreatedAt = createdAt;
            Devices = devices;
            Frequency = frequency;
            Id = id;
            LocationIds = locationIds;
            Name = name;
            Requests = requests;
            SchedulingStrategy = schedulingStrategy;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
