// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsBrowserV2CheckTestBusinessTransactionResult
    {
        public readonly string? Name;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestBusinessTransactionStepResult> Steps;

        [OutputConstructor]
        private SyntheticsBrowserV2CheckTestBusinessTransactionResult(
            string? name,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestBusinessTransactionStepResult> steps)
        {
            Name = name;
            Steps = steps;
        }
    }
}
