// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCheckLinkResult
    {
        public readonly string LastRun;
        public readonly string Metrics;
        public readonly string Self;
        public readonly string SelfHtml;

        [OutputConstructor]
        private SyntheticsCheckLinkResult(
            string lastRun,

            string metrics,

            string self,

            string selfHtml)
        {
            LastRun = lastRun;
            Metrics = metrics;
            Self = self;
            SelfHtml = selfHtml;
        }
    }
}
