// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCreateBrowserCheckV2TestAdvancedSettingHostOverride
    {
        public readonly bool? KeepHostHeader;
        public readonly string? Source;
        public readonly string? Target;

        [OutputConstructor]
        private SyntheticsCreateBrowserCheckV2TestAdvancedSettingHostOverride(
            bool? keepHostHeader,

            string? source,

            string? target)
        {
            KeepHostHeader = keepHostHeader;
            Source = source;
            Target = target;
        }
    }
}
