// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCreateBrowserCheckV2Test
    {
        public readonly bool? Active;
        public readonly ImmutableArray<Outputs.SyntheticsCreateBrowserCheckV2TestAdvancedSetting> AdvancedSettings;
        public readonly int? DeviceId;
        public readonly int? Frequency;
        public readonly ImmutableArray<string> LocationIds;
        public readonly string Name;
        public readonly string? SchedulingStrategy;
        public readonly string StartUrl;
        public readonly ImmutableArray<Outputs.SyntheticsCreateBrowserCheckV2TestTransaction> Transactions;
        public readonly string UrlProtocol;

        [OutputConstructor]
        private SyntheticsCreateBrowserCheckV2Test(
            bool? active,

            ImmutableArray<Outputs.SyntheticsCreateBrowserCheckV2TestAdvancedSetting> advancedSettings,

            int? deviceId,

            int? frequency,

            ImmutableArray<string> locationIds,

            string name,

            string? schedulingStrategy,

            string startUrl,

            ImmutableArray<Outputs.SyntheticsCreateBrowserCheckV2TestTransaction> transactions,

            string urlProtocol)
        {
            Active = active;
            AdvancedSettings = advancedSettings;
            DeviceId = deviceId;
            Frequency = frequency;
            LocationIds = locationIds;
            Name = name;
            SchedulingStrategy = schedulingStrategy;
            StartUrl = startUrl;
            Transactions = transactions;
            UrlProtocol = urlProtocol;
        }
    }
}
