// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsHttpV2CheckTestResult
    {
        public readonly bool Active;
        public readonly string Body;
        public readonly string CreatedAt;
        public readonly int Frequency;
        public readonly ImmutableArray<Outputs.SyntheticsHttpV2CheckTestHeaderResult> Headers;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int Id;
        public readonly ImmutableArray<string> LocationIds;
        public readonly string Name;
        public readonly string RequestMethod;
        public readonly string SchedulingStrategy;
        public readonly string Type;
        public readonly string UpdatedAt;
        public readonly string Url;

        [OutputConstructor]
        private SyntheticsHttpV2CheckTestResult(
            bool active,

            string body,

            string createdAt,

            int frequency,

            ImmutableArray<Outputs.SyntheticsHttpV2CheckTestHeaderResult> headers,

            int id,

            ImmutableArray<string> locationIds,

            string name,

            string requestMethod,

            string schedulingStrategy,

            string type,

            string updatedAt,

            string url)
        {
            Active = active;
            Body = body;
            CreatedAt = createdAt;
            Frequency = frequency;
            Headers = headers;
            Id = id;
            LocationIds = locationIds;
            Name = name;
            RequestMethod = requestMethod;
            SchedulingStrategy = schedulingStrategy;
            Type = type;
            UpdatedAt = updatedAt;
            Url = url;
        }
    }
}
