// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCreateBrowserCheckJavascriptFile
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int? Id;
        public readonly string? Name;

        [OutputConstructor]
        private SyntheticsCreateBrowserCheckJavascriptFile(
            int? id,

            string? name)
        {
            Id = id;
            Name = name;
        }
    }
}
