// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCreateBrowserCheckStep
    {
        public readonly string? How;
        public readonly string? ItemMethod;
        public readonly string? Name;
        public readonly int? Position;
        public readonly string? Value;
        public readonly string? VariableName;
        public readonly string? What;

        [OutputConstructor]
        private SyntheticsCreateBrowserCheckStep(
            string? how,

            string? itemMethod,

            string? name,

            int? position,

            string? value,

            string? variableName,

            string? what)
        {
            How = how;
            ItemMethod = itemMethod;
            Name = name;
            Position = position;
            Value = value;
            VariableName = variableName;
            What = what;
        }
    }
}
