// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsBrowserV2CheckTestAdvancedSettingResult
    {
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingAuthenticationResult> Authentications;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingCookieResult> Cookies;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingHeaderResult> Headers;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingHostOverrideResult> HostOverrides;
        public readonly string UserAgent;
        public readonly bool VerifyCertificates;

        [OutputConstructor]
        private SyntheticsBrowserV2CheckTestAdvancedSettingResult(
            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingAuthenticationResult> authentications,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingCookieResult> cookies,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingHeaderResult> headers,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingHostOverrideResult> hostOverrides,

            string userAgent,

            bool verifyCertificates)
        {
            Authentications = authentications;
            Cookies = cookies;
            Headers = headers;
            HostOverrides = hostOverrides;
            UserAgent = userAgent;
            VerifyCertificates = verifyCertificates;
        }
    }
}
