// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsApiV2CheckTestRequestResult
    {
        public readonly ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestConfigurationResult> Configurations;
        public readonly ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestSetupResult> Setups;
        public readonly ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestValidationResult> Validations;

        [OutputConstructor]
        private SyntheticsApiV2CheckTestRequestResult(
            ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestConfigurationResult> configurations,

            ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestSetupResult> setups,

            ImmutableArray<Outputs.SyntheticsApiV2CheckTestRequestValidationResult> validations)
        {
            Configurations = configurations;
            Setups = setups;
            Validations = validations;
        }
    }
}
