// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsApiV2CheckTestRequestSetupResult
    {
        public readonly string? Extractor;
        public readonly string? Name;
        public readonly string? Source;
        public readonly string? Type;
        public readonly string? Variable;

        [OutputConstructor]
        private SyntheticsApiV2CheckTestRequestSetupResult(
            string? extractor,

            string? name,

            string? source,

            string? type,

            string? variable)
        {
            Extractor = extractor;
            Name = name;
            Source = source;
            Type = type;
            Variable = variable;
        }
    }
}
