// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCheckCheckConnectionResult
    {
        public readonly int DownloadBandwidth;
        public readonly int Latency;
        public readonly int PacketLoss;
        public readonly int UploadBandwidth;

        [OutputConstructor]
        private SyntheticsCheckCheckConnectionResult(
            int downloadBandwidth,

            int latency,

            int packetLoss,

            int uploadBandwidth)
        {
            DownloadBandwidth = downloadBandwidth;
            Latency = latency;
            PacketLoss = packetLoss;
            UploadBandwidth = uploadBandwidth;
        }
    }
}
