// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCreateHttpCheckNotificationEscalationNotifyWho
    {
        public readonly bool? Call;
        public readonly string? CustomUserEmail;
        public readonly bool? Email;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int? Id;
        public readonly ImmutableArray<Outputs.SyntheticsCreateHttpCheckNotificationEscalationNotifyWhoLink> Links;
        public readonly bool? Sms;
        public readonly string? Type;

        [OutputConstructor]
        private SyntheticsCreateHttpCheckNotificationEscalationNotifyWho(
            bool? call,

            string? customUserEmail,

            bool? email,

            int? id,

            ImmutableArray<Outputs.SyntheticsCreateHttpCheckNotificationEscalationNotifyWhoLink> links,

            bool? sms,

            string? type)
        {
            Call = call;
            CustomUserEmail = customUserEmail;
            Email = email;
            Id = id;
            Links = links;
            Sms = sms;
            Type = type;
        }
    }
}
