// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsBrowserV2CheckTestResult
    {
        public readonly bool Active;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingResult> AdvancedSettings;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestBusinessTransactionResult> BusinessTransactions;
        public readonly string CreatedAt;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestDeviceResult> Devices;
        public readonly int Frequency;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int Id;
        public readonly ImmutableArray<string> LocationIds;
        public readonly string Name;
        public readonly string SchedulingStrategy;
        public readonly ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestTransactionResult> Transactions;
        public readonly string Type;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private SyntheticsBrowserV2CheckTestResult(
            bool active,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestAdvancedSettingResult> advancedSettings,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestBusinessTransactionResult> businessTransactions,

            string createdAt,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestDeviceResult> devices,

            int frequency,

            int id,

            ImmutableArray<string> locationIds,

            string name,

            string schedulingStrategy,

            ImmutableArray<Outputs.SyntheticsBrowserV2CheckTestTransactionResult> transactions,

            string type,

            string updatedAt)
        {
            Active = active;
            AdvancedSettings = advancedSettings;
            BusinessTransactions = businessTransactions;
            CreatedAt = createdAt;
            Devices = devices;
            Frequency = frequency;
            Id = id;
            LocationIds = locationIds;
            Name = name;
            SchedulingStrategy = schedulingStrategy;
            Transactions = transactions;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
