// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Outputs
{

    [OutputType]
    public sealed class SyntheticsCheckSuccessCriteriaResult
    {
        public readonly string ActionType;
        public readonly string ComparisonString;
        public readonly string CreatedAt;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private SyntheticsCheckSuccessCriteriaResult(
            string actionType,

            string comparisonString,

            string createdAt,

            string updatedAt)
        {
            ActionType = actionType;
            ComparisonString = comparisonString;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
        }
    }
}
