// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/displayr/pulumi-signalfx-synthetics/sdk/go/synthetics/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Splunk Observability API Key. Will pull from `OBSERVABILITY_API_TOKEN` environment variable if available.
func GetApikey(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "synthetics:apikey")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "OBSERVABILITY_API_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// One of: `observability` or `rigor`
func GetProduct(ctx *pulumi.Context) string {
	return config.Get(ctx, "synthetics:product")
}

// Splunk Observability Realm (E.G. `us1`). Will pull from `REALM` environment variable if available. For Rigor use realm
// rigor
func GetRealm(ctx *pulumi.Context) string {
	return config.Get(ctx, "synthetics:realm")
}
