// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCreateApiCheckV2TestRequestGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("configurations")]
        private InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestConfigurationGetArgs>? _configurations;
        public InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestConfigurationGetArgs> Configurations
        {
            get => _configurations ?? (_configurations = new InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestConfigurationGetArgs>());
            set => _configurations = value;
        }

        [Input("setups")]
        private InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestSetupGetArgs>? _setups;
        public InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestSetupGetArgs> Setups
        {
            get => _setups ?? (_setups = new InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestSetupGetArgs>());
            set => _setups = value;
        }

        [Input("validations")]
        private InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestValidationGetArgs>? _validations;
        public InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestValidationGetArgs> Validations
        {
            get => _validations ?? (_validations = new InputList<Inputs.SyntheticsCreateApiCheckV2TestRequestValidationGetArgs>());
            set => _validations = value;
        }

        public SyntheticsCreateApiCheckV2TestRequestGetArgs()
        {
        }
        public static new SyntheticsCreateApiCheckV2TestRequestGetArgs Empty => new SyntheticsCreateApiCheckV2TestRequestGetArgs();
    }
}
