// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCreateBrowserCheckV2TestAdvancedSettingArgs : global::Pulumi.ResourceArgs
    {
        [Input("authentications")]
        private InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingAuthenticationArgs>? _authentications;
        public InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingAuthenticationArgs> Authentications
        {
            get => _authentications ?? (_authentications = new InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingAuthenticationArgs>());
            set => _authentications = value;
        }

        [Input("cookies")]
        private InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingCookieArgs>? _cookies;
        public InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingCookieArgs> Cookies
        {
            get => _cookies ?? (_cookies = new InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingCookieArgs>());
            set => _cookies = value;
        }

        [Input("headers")]
        private InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingHeaderArgs>? _headers;
        public InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingHeaderArgs> Headers
        {
            get => _headers ?? (_headers = new InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingHeaderArgs>());
            set => _headers = value;
        }

        [Input("hostOverrides")]
        private InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingHostOverrideArgs>? _hostOverrides;
        public InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingHostOverrideArgs> HostOverrides
        {
            get => _hostOverrides ?? (_hostOverrides = new InputList<Inputs.SyntheticsCreateBrowserCheckV2TestAdvancedSettingHostOverrideArgs>());
            set => _hostOverrides = value;
        }

        [Input("userAgent")]
        public Input<string>? UserAgent { get; set; }

        [Input("verifyCertificates")]
        public Input<bool>? VerifyCertificates { get; set; }

        public SyntheticsCreateBrowserCheckV2TestAdvancedSettingArgs()
        {
        }
        public static new SyntheticsCreateBrowserCheckV2TestAdvancedSettingArgs Empty => new SyntheticsCreateBrowserCheckV2TestAdvancedSettingArgs();
    }
}
