// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCheckLinkArgs : global::Pulumi.InvokeArgs
    {
        [Input("lastRun", required: true)]
        public string LastRun { get; set; } = null!;

        [Input("metrics", required: true)]
        public string Metrics { get; set; } = null!;

        [Input("self", required: true)]
        public string Self { get; set; } = null!;

        [Input("selfHtml", required: true)]
        public string SelfHtml { get; set; } = null!;

        public SyntheticsCheckLinkArgs()
        {
        }
        public static new SyntheticsCheckLinkArgs Empty => new SyntheticsCheckLinkArgs();
    }
}
