// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCheckViewportArgs : global::Pulumi.InvokeArgs
    {
        [Input("height")]
        public int? Height { get; set; }

        [Input("width")]
        public int? Width { get; set; }

        public SyntheticsCheckViewportArgs()
        {
        }
        public static new SyntheticsCheckViewportArgs Empty => new SyntheticsCheckViewportArgs();
    }
}
