// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsBrowserV2CheckTestBusinessTransactionStepInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<string>? Action { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("optionSelector")]
        public Input<string>? OptionSelector { get; set; }

        [Input("optionSelectorType")]
        public Input<string>? OptionSelectorType { get; set; }

        [Input("options", required: true)]
        private InputList<Inputs.SyntheticsBrowserV2CheckTestBusinessTransactionStepOptionInputArgs>? _options;
        public InputList<Inputs.SyntheticsBrowserV2CheckTestBusinessTransactionStepOptionInputArgs> Options
        {
            get => _options ?? (_options = new InputList<Inputs.SyntheticsBrowserV2CheckTestBusinessTransactionStepOptionInputArgs>());
            set => _options = value;
        }

        [Input("selector")]
        public Input<string>? Selector { get; set; }

        [Input("selectorType")]
        public Input<string>? SelectorType { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        [Input("variableName")]
        public Input<string>? VariableName { get; set; }

        [Input("waitForNav")]
        public Input<bool>? WaitForNav { get; set; }

        public SyntheticsBrowserV2CheckTestBusinessTransactionStepInputArgs()
        {
        }
        public static new SyntheticsBrowserV2CheckTestBusinessTransactionStepInputArgs Empty => new SyntheticsBrowserV2CheckTestBusinessTransactionStepInputArgs();
    }
}
