// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCreateBrowserCheckV2TestTransactionStepOptionArgs : global::Pulumi.ResourceArgs
    {
        [Input("url")]
        public Input<string>? Url { get; set; }

        public SyntheticsCreateBrowserCheckV2TestTransactionStepOptionArgs()
        {
        }
        public static new SyntheticsCreateBrowserCheckV2TestTransactionStepOptionArgs Empty => new SyntheticsCreateBrowserCheckV2TestTransactionStepOptionArgs();
    }
}
