// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCheckBrowserArgs : global::Pulumi.InvokeArgs
    {
        [Input("type")]
        public string? Type { get; set; }

        public SyntheticsCheckBrowserArgs()
        {
        }
        public static new SyntheticsCheckBrowserArgs Empty => new SyntheticsCheckBrowserArgs();
    }
}
