// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsLocationV2CheckMetaInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("activeTestIds", required: true)]
        private InputList<int>? _activeTestIds;
        public InputList<int> ActiveTestIds
        {
            get => _activeTestIds ?? (_activeTestIds = new InputList<int>());
            set => _activeTestIds = value;
        }

        [Input("pausedTestIds", required: true)]
        private InputList<int>? _pausedTestIds;
        public InputList<int> PausedTestIds
        {
            get => _pausedTestIds ?? (_pausedTestIds = new InputList<int>());
            set => _pausedTestIds = value;
        }

        public SyntheticsLocationV2CheckMetaInputArgs()
        {
        }
        public static new SyntheticsLocationV2CheckMetaInputArgs Empty => new SyntheticsLocationV2CheckMetaInputArgs();
    }
}
