// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsVariableV2CheckVariableArgs : global::Pulumi.InvokeArgs
    {
        [Input("createdAt", required: true)]
        public string CreatedAt { get; set; } = null!;

        [Input("description", required: true)]
        public string Description { get; set; } = null!;

        /// <summary>
        /// The ID of this resource.
        /// </summary>
        [Input("id", required: true)]
        public int Id { get; set; }

        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("secret", required: true)]
        public bool Secret { get; set; }

        [Input("updatedAt", required: true)]
        public string UpdatedAt { get; set; } = null!;

        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public SyntheticsVariableV2CheckVariableArgs()
        {
        }
        public static new SyntheticsVariableV2CheckVariableArgs Empty => new SyntheticsVariableV2CheckVariableArgs();
    }
}
