// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsDevicesV2CheckDeviceNetworkConnectionArgs : global::Pulumi.InvokeArgs
    {
        [Input("description", required: true)]
        public string Description { get; set; } = null!;

        [Input("downloadBandwidth", required: true)]
        public int DownloadBandwidth { get; set; }

        [Input("latency", required: true)]
        public int Latency { get; set; }

        [Input("packetLoss", required: true)]
        public int PacketLoss { get; set; }

        [Input("uploadBandwidth")]
        public int? UploadBandwidth { get; set; }

        public SyntheticsDevicesV2CheckDeviceNetworkConnectionArgs()
        {
        }
        public static new SyntheticsDevicesV2CheckDeviceNetworkConnectionArgs Empty => new SyntheticsDevicesV2CheckDeviceNetworkConnectionArgs();
    }
}
