// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCheckDnsOverrideArgs : global::Pulumi.InvokeArgs
    {
        [Input("originalDomain")]
        public string? OriginalDomain { get; set; }

        [Input("originalHost")]
        public string? OriginalHost { get; set; }

        public SyntheticsCheckDnsOverrideArgs()
        {
        }
        public static new SyntheticsCheckDnsOverrideArgs Empty => new SyntheticsCheckDnsOverrideArgs();
    }
}
