// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsApiV2CheckTestInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("active", required: true)]
        public Input<bool> Active { get; set; } = null!;

        [Input("createdAt", required: true)]
        public Input<string> CreatedAt { get; set; } = null!;

        [Input("devices", required: true)]
        private InputList<Inputs.SyntheticsApiV2CheckTestDeviceInputArgs>? _devices;
        public InputList<Inputs.SyntheticsApiV2CheckTestDeviceInputArgs> Devices
        {
            get => _devices ?? (_devices = new InputList<Inputs.SyntheticsApiV2CheckTestDeviceInputArgs>());
            set => _devices = value;
        }

        [Input("frequency", required: true)]
        public Input<int> Frequency { get; set; } = null!;

        /// <summary>
        /// The ID of this resource.
        /// </summary>
        [Input("id", required: true)]
        public Input<int> Id { get; set; } = null!;

        [Input("locationIds")]
        private InputList<string>? _locationIds;
        public InputList<string> LocationIds
        {
            get => _locationIds ?? (_locationIds = new InputList<string>());
            set => _locationIds = value;
        }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("requests", required: true)]
        private InputList<Inputs.SyntheticsApiV2CheckTestRequestInputArgs>? _requests;
        public InputList<Inputs.SyntheticsApiV2CheckTestRequestInputArgs> Requests
        {
            get => _requests ?? (_requests = new InputList<Inputs.SyntheticsApiV2CheckTestRequestInputArgs>());
            set => _requests = value;
        }

        [Input("schedulingStrategy", required: true)]
        public Input<string> SchedulingStrategy { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("updatedAt", required: true)]
        public Input<string> UpdatedAt { get; set; } = null!;

        public SyntheticsApiV2CheckTestInputArgs()
        {
        }
        public static new SyntheticsApiV2CheckTestInputArgs Empty => new SyntheticsApiV2CheckTestInputArgs();
    }
}
