// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsBrowserV2CheckTestAdvancedSettingAuthenticationArgs : global::Pulumi.InvokeArgs
    {
        [Input("password")]
        public string? Password { get; set; }

        [Input("username")]
        public string? Username { get; set; }

        public SyntheticsBrowserV2CheckTestAdvancedSettingAuthenticationArgs()
        {
        }
        public static new SyntheticsBrowserV2CheckTestAdvancedSettingAuthenticationArgs Empty => new SyntheticsBrowserV2CheckTestAdvancedSettingAuthenticationArgs();
    }
}
