// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsBrowserV2CheckTestDeviceInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("id", required: true)]
        public Input<int> Id { get; set; } = null!;

        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        [Input("networkConnections", required: true)]
        private InputList<Inputs.SyntheticsBrowserV2CheckTestDeviceNetworkConnectionInputArgs>? _networkConnections;
        public InputList<Inputs.SyntheticsBrowserV2CheckTestDeviceNetworkConnectionInputArgs> NetworkConnections
        {
            get => _networkConnections ?? (_networkConnections = new InputList<Inputs.SyntheticsBrowserV2CheckTestDeviceNetworkConnectionInputArgs>());
            set => _networkConnections = value;
        }

        [Input("userAgent", required: true)]
        public Input<string> UserAgent { get; set; } = null!;

        [Input("viewportHeight")]
        public Input<int>? ViewportHeight { get; set; }

        [Input("viewportWidth")]
        public Input<int>? ViewportWidth { get; set; }

        public SyntheticsBrowserV2CheckTestDeviceInputArgs()
        {
        }
        public static new SyntheticsBrowserV2CheckTestDeviceInputArgs Empty => new SyntheticsBrowserV2CheckTestDeviceInputArgs();
    }
}
