// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsBrowserV2CheckTestDeviceNetworkConnectionArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public string? Description { get; set; }

        [Input("downloadBandwidth")]
        public int? DownloadBandwidth { get; set; }

        [Input("latency")]
        public int? Latency { get; set; }

        [Input("packetLoss")]
        public int? PacketLoss { get; set; }

        [Input("uploadBandwidth")]
        public int? UploadBandwidth { get; set; }

        public SyntheticsBrowserV2CheckTestDeviceNetworkConnectionArgs()
        {
        }
        public static new SyntheticsBrowserV2CheckTestDeviceNetworkConnectionArgs Empty => new SyntheticsBrowserV2CheckTestDeviceNetworkConnectionArgs();
    }
}
