// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCheckLinkInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("lastRun", required: true)]
        public Input<string> LastRun { get; set; } = null!;

        [Input("metrics", required: true)]
        public Input<string> Metrics { get; set; } = null!;

        [Input("self", required: true)]
        public Input<string> Self { get; set; } = null!;

        [Input("selfHtml", required: true)]
        public Input<string> SelfHtml { get; set; } = null!;

        public SyntheticsCheckLinkInputArgs()
        {
        }
        public static new SyntheticsCheckLinkInputArgs Empty => new SyntheticsCheckLinkInputArgs();
    }
}
