// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCreateBrowserCheckV2TestTransactionArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("steps", required: true)]
        private InputList<Inputs.SyntheticsCreateBrowserCheckV2TestTransactionStepArgs>? _steps;
        public InputList<Inputs.SyntheticsCreateBrowserCheckV2TestTransactionStepArgs> Steps
        {
            get => _steps ?? (_steps = new InputList<Inputs.SyntheticsCreateBrowserCheckV2TestTransactionStepArgs>());
            set => _steps = value;
        }

        public SyntheticsCreateBrowserCheckV2TestTransactionArgs()
        {
        }
        public static new SyntheticsCreateBrowserCheckV2TestTransactionArgs Empty => new SyntheticsCreateBrowserCheckV2TestTransactionArgs();
    }
}
