// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsBrowserV2CheckTestAdvancedSettingCookieArgs : global::Pulumi.InvokeArgs
    {
        [Input("domain")]
        public string? Domain { get; set; }

        [Input("key")]
        public string? Key { get; set; }

        [Input("path")]
        public string? Path { get; set; }

        [Input("value")]
        public string? Value { get; set; }

        public SyntheticsBrowserV2CheckTestAdvancedSettingCookieArgs()
        {
        }
        public static new SyntheticsBrowserV2CheckTestAdvancedSettingCookieArgs Empty => new SyntheticsBrowserV2CheckTestAdvancedSettingCookieArgs();
    }
}
