// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Synthetics.Inputs
{

    public sealed class SyntheticsCreateLocationV2LocationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("country")]
        public Input<string>? Country { get; set; }

        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// The ID of this resource.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        [Input("type")]
        public Input<string>? Type { get; set; }

        public SyntheticsCreateLocationV2LocationGetArgs()
        {
        }
        public static new SyntheticsCreateLocationV2LocationGetArgs Empty => new SyntheticsCreateLocationV2LocationGetArgs();
    }
}
