name: Comment Post-Merge Run Links

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  comment-run-links:
    uses: Displayr/gh-workflows/.github/workflows/comment-post-merge-run-links.yml@main
    with:
      runs-on: ${{ vars.GHA_RUNS_ON_JSON || '["self-hosted","linux"]' }}
      workflow-name-regex: ${{ vars.WORKFLOW_NAME_REGEX || 'pulumi|deploy|build' }}
      workflow-owner-repo: ${{ vars.WORKFLOW_OWNER_REPO || github.repository }}
      circleci-project-slug: ${{ vars.CIRCLECI_PROJECT_SLUG || '' }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      circleci_token: ${{ secrets.CIRCLECI_TOKEN }}
