// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as synthetics from "@pulumi/synthetics";
 *
 * const datasourceCheckPort = synthetics.syntheticsPortV2Check({
 *     tests: [{
 *         id: 1650,
 *     }],
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function syntheticsPortV2Check(args: SyntheticsPortV2CheckArgs, opts?: pulumi.InvokeOptions): Promise<SyntheticsPortV2CheckResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("synthetics:index/syntheticsPortV2Check:syntheticsPortV2Check", {
        "tests": args.tests,
    }, opts);
}

/**
 * A collection of arguments for invoking syntheticsPortV2Check.
 */
export interface SyntheticsPortV2CheckArgs {
    tests: inputs.SyntheticsPortV2CheckTest[];
}

/**
 * A collection of values returned by syntheticsPortV2Check.
 */
export interface SyntheticsPortV2CheckResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly tests: outputs.SyntheticsPortV2CheckTest[];
}
/**
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as synthetics from "@pulumi/synthetics";
 *
 * const datasourceCheckPort = synthetics.syntheticsPortV2Check({
 *     tests: [{
 *         id: 1650,
 *     }],
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function syntheticsPortV2CheckOutput(args: SyntheticsPortV2CheckOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<SyntheticsPortV2CheckResult> {
    return pulumi.output(args).apply((a: any) => syntheticsPortV2Check(a, opts))
}

/**
 * A collection of arguments for invoking syntheticsPortV2Check.
 */
export interface SyntheticsPortV2CheckOutputArgs {
    tests: pulumi.Input<pulumi.Input<inputs.SyntheticsPortV2CheckTestArgs>[]>;
}
